### ISSUE TITLE
Nicer word wrapping / resizing for a long deck name

### ISSUE THREAD

**Issue by ES-Anon** [TechWithTyler/FlexiDeck#20]
If I give my deck a name that is, say 15 characters, I might expect the font size to lower to allow it to fit on a single line, when viewing in "list of cards" view.

For even longer deck names, it might be worth wrapping to a 2nd line?

![IMG_3383C286D0C0-1](https://github.com/user-attachments/assets/54db10ab-5fd5-41d5-a8e0-0a73a94caaab)

**Comment by TechWithTyler** [comment]
Unfortunately, SwiftUI doesn't offer this ability.
