### ISSUE TITLE
Refine New Card UX - Straight to detail view after creating

### ISSUE THREAD

**Issue by ES-Anon** [TechWithTyler/FlexiDeck#23]
As a user, I would like to dive straight into adding content to a card after creating it. I would expect that the new card would follow the deck-setting re: 1-sided or 2.

The present flow of being presented with the card-settings view does not feel intuitive. 

We should consider the "Card Title" flow in this . . . I'm interested in potentially following Apple's Notes, in which Title is not a specific field that a user has to specify, but is simply automatically "whatever is on the first line of the note is displayed as the title"

**Comment by TechWithTyler** [comment]
You can turn off the auto showing of the card/deck settings after creating.

**Comment by ES-Anon** [comment]
I would like the "straight to detail view" to be the default behavior; then we can close this. Thanks!
