### ISSUE TITLE
Refine New Card UX flow - New Card creation is hidden in a menu

### ISSUE THREAD

**Issue by ES-Anon** [TechWithTyler/FlexiDeck#24]
As a user running their iOS set to Display Zoom -> Larger Text, when presented with my list of cards, it is not immediately clear how I would add a new card.

Top preference: A "New Card" button at the bottom of the list view. This button could be creatively shown and hidden based on:
1. whether user is at the bottom of their list
2. Whether user has just scrolled up or down, like how Safari on an iPhone shows + hides the address bar

![IMG_6237](https://github.com/user-attachments/assets/d90507d5-b1ae-44e9-bda3-deb7a8e91ab0)

If that route is too difficult, adding a "New card" icon to header or footer, like the New Note icon in Apple's Notes would work too.

**Comment by ES-Anon** [comment]
@TechWithTyler Can you clarify what commit closed this issue? I don't see the desired behavior reflected in the current build (103), and did not see this issue referenced in any recent commit.

**Comment by TechWithTyler** [comment]
Commit with SHA b40f2bd402fa5181036517507c7f345dc36c1845. Not sure how to get the number.

**Comment by TechWithTyler** [comment]
Add button is out of the menu. Not sure why you’re not seeing that.

**Comment by ES-Anon** [comment]
![IMG_A5BBF0F9EDFB-1](https://github.com/user-attachments/assets/dba80b63-7743-4135-a1fd-e1500ce59d5c)
