### ISSUE TITLE
Card [...] menu disappears after adding text, and cannot flip

### ISSUE THREAD

**Issue by ES-Anon** [TechWithTyler/FlexiDeck#25]
### Reproduction steps:
1. Create a deck, set to "1-sided" as default
2. Create a new 2-sided card
3. Add text to front of card
4. Return to "list of cards" view
5. Select the newly created card

### Expected
I see the [...] menu in top right corner, and can view the back of the card

### Actual
[...] menu is missing

**Comment by TechWithTyler** [comment]
Do you mean “set the deck to 2-sided as default”?
This is a SwiftUI bug. SwiftUI isn’t bug-free yet…
